# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CricketFantasy.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sqlite3
db=sqlite3.connect("team.db")
cur=db.cursor()
from PyQt5.QtWidgets import QMessageBox
from Evaluation import Ui_Form
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.batcount=0
        self.ballcount=0
        self.arcount=0
        self.wkcount=0
        self.point_avl=1000
        self.point_use=0
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(764, 612)
        MainWindow.setStyleSheet("QMainWindow{\n""background-color:qlineargradient(spread:pad, x1:1, y1:0.403, x2:0.17, y2:0.420455,stop:0 rgba(255, 85, 255, 255),stop:1 rgba(255, 255, 255, 255));\n""}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.l1 = QtWidgets.QLineEdit(self.centralwidget)
        self.l1.setReadOnly(True)
        self.l1.setObjectName("l1")
        self.horizontalLayout_7.addWidget(self.l1)
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.l2 = QtWidgets.QLineEdit(self.centralwidget)
        self.l2.setReadOnly(True)
        self.l2.setObjectName("l2")
        self.horizontalLayout_7.addWidget(self.l2)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.l3 = QtWidgets.QLineEdit(self.centralwidget)
        self.l3.setReadOnly(True)
        self.l3.setObjectName("l3")
        self.horizontalLayout_7.addWidget(self.l3)
        spacerItem2 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.l4 = QtWidgets.QLineEdit(self.centralwidget)
        self.l4.setReadOnly(True)
        self.l4.setObjectName("l4")
        self.horizontalLayout_7.addWidget(self.l4)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.r1 = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.r1.setFont(font)
        self.r1.setObjectName("r1")
        self.horizontalLayout_8.addWidget(self.r1)
        self.r2 = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.r2.setFont(font)
        self.r2.setObjectName("r2")
        self.horizontalLayout_8.addWidget(self.r2)
        self.r3 = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.r3.setFont(font)
        self.r3.setObjectName("r3")
        self.horizontalLayout_8.addWidget(self.r3)
        self.r4 = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.r4.setFont(font)
        self.r4.setObjectName("r4")
        self.horizontalLayout_8.addWidget(self.r4)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 3)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_12.addWidget(self.label_10)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_12.addWidget(self.lineEdit_7)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_12, 1, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem4 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_10.addWidget(self.lineEdit_5)
        spacerItem5 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout_10, 1, 1, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem6 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem6)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_11.addWidget(self.label_9)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_11.addWidget(self.lineEdit_6)
        spacerItem7 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.gridLayout.addLayout(self.horizontalLayout_11, 1, 2, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("../../../../Users/Karishma Dubey/Videos/11 (2).jpeg"))
        self.label_12.setObjectName("label_12")
        self.verticalLayout_4.addWidget(self.label_12)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem8)
        self.gridLayout.addLayout(self.verticalLayout_4, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem9 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        spacerItem10 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setObjectName("listWidget_2")
        self.verticalLayout_3.addWidget(self.listWidget_2)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAutoFillBackground(False)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_3.addWidget(self.label_13)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 764, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_Game = QtWidgets.QAction(MainWindow)
        self.actionNew_Game.setObjectName("actionNew_Game")
        self.actionOpen_Team = QtWidgets.QAction(MainWindow)
        self.actionOpen_Team.setObjectName("actionOpen_Team")
        self.actionSave_Team = QtWidgets.QAction(MainWindow)
        self.actionSave_Team.setObjectName("actionSave_Team")
        self.actionEvaluate_Team = QtWidgets.QAction(MainWindow)
        self.actionEvaluate_Team.setObjectName("actionEvaluate_Team")
        self.actionTotal_players_11 = QtWidgets.QAction(MainWindow)
        self.actionTotal_players_11.setObjectName("actionTotal_players_11")
        self.actionTotal_Points_300 = QtWidgets.QAction(MainWindow)
        self.actionTotal_Points_300.setObjectName("actionTotal_Points_300")
        self.menuFile.addAction(self.actionNew_Game)
        self.menuFile.addAction(self.actionOpen_Team)
        self.menuFile.addAction(self.actionSave_Team)
        self.menuFile.addAction(self.actionEvaluate_Team)
        self.menubar.addAction(self.menuFile.menuAction())

        self.r1.clicked.connect(self.radio)
        self.r2.clicked.connect(self.radio)
        self.r3.clicked.connect(self.radio)
        self.r4.clicked.connect(self.radio)
        self.listWidget.itemDoubleClicked.connect(self.removelist1)
        self.listWidget_2.itemDoubleClicked.connect(self.removelist2)
        self.actionEvaluate_Team.triggered.connect(self.evaluate_show)
        self.actionSave_Team.triggered.connect(self.save)
        self.actionNew_Game.triggered.connect(self.team_show)
        self.actionOpen_Team.triggered.connect(self.open_team)
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cricket Fantasy Game"))
        self.label_4.setText(_translate("MainWindow", "Your Selections"))
        self.label_5.setText(_translate("MainWindow", "Batsmen(BAT)"))
        self.label_3.setText(_translate("MainWindow", "Bowlers(BOW)"))
        self.label_6.setText(_translate("MainWindow", "All- Rounders(AR)"))
        self.label_7.setText(_translate("MainWindow", "Wicket-Keeper(WK)"))
        self.l1.setText("0")
        self.l2.setText("0")
        self.l3.setText("0")
        self.l4.setText("0")
        self.lineEdit_7.setText('')
        self.lineEdit_5.setText('1000')
        self.lineEdit_6.setText('0')
        self.r1.setText(_translate("MainWindow", "BAT"))
        self.r2.setText(_translate("MainWindow", "BOW"))
        self.r3.setText(_translate("MainWindow", "AR"))
        self.r4.setText(_translate("MainWindow", "WK"))
        self.label_10.setText(_translate("MainWindow", "Team Name"))
        self.label_8.setText(_translate("MainWindow", "Points Available"))
        self.label_9.setText(_translate("MainWindow", "Points Used"))
        self.label_2.setText(_translate("MainWindow", "            AVAILABLE PLAYERS"))
        self.label_11.setText(_translate("MainWindow", ">>>>"))
        self.label_13.setText(_translate("MainWindow", "              SELECTED PLAYERS"))
        self.menuFile.setTitle(_translate("MainWindow", "Manage Teams"))
        self.actionNew_Game.setText(_translate("MainWindow", "New Team"))
        self.actionOpen_Team.setText(_translate("MainWindow", "Open Team"))
        self.actionSave_Team.setText(_translate("MainWindow", "Save Team"))
        self.actionEvaluate_Team.setText(_translate("MainWindow", "Evaluate Team"))
        self.actionTotal_players_11.setText(_translate("MainWindow", "Total players=11"))
        self.actionTotal_Points_300.setText(_translate("MainWindow", "Total Points=300"))

    #selecting team members
    def radio(self):
        if self.lineEdit_7.text()=='':
            self.message_box("Oops!Team Name is Empty")
        else:
            if self.r1.isChecked()==True:
                self.select("bat")
            
            elif self.r2.isChecked()==True:
                self.select("bwl")
            
            elif self.r3.isChecked()==True:
                self.select("ar")
             
            elif self.r4.isChecked()==True:
                self.select("wk")
            
    def select(self,ct):
        c=cur.execute("SELECT Player FROM stats WHERE ctg=='"+ct+"'")
        self.listWidget.clear()
        for row in c:
            selected=[]
            for i in range(self.listWidget_2.count()):
                selected.append(self.listWidget_2.item(i).text())
            if row[0] not in selected:
                self.listWidget.addItem(row[0])
                
    #Message Box        
    def message_box(self,mg):
        msg=QMessageBox()
        msg.setWindowTitle(" ")
        msg.setText(''+mg+'')
        msg.setIcon(QMessageBox.Critical)
        msg.exec_()

    #removing list1 items
    def removelist1(self,item):
        self.listWidget.row(item)
        cur.execute("SELECT [Values] FROM stats WHERE Player=='"+item.text()+"'")
        r=cur.fetchone()
        self.point_avl-=r[0]
        self.point_use+=r[0]
        if self.point_avl<=0:
            self.message_box("Insufficient Points")
            self.point_avl+=r[0]
            self.point_use-=r[0]
        
        else:
            if self.r1.isChecked()==True:
                self.batcount+=1
                if self.batcount>5:
                    self.message_box("You can't select more than five Batsmen") 
                    self.batcount-=1
                    self.point_avl+=r[0]
                    self.point_use-=r[0]
                else:
                    self.listWidget.takeItem(self.listWidget.row(item))
                    self.listWidget_2.addItem(item.text())
                    self.l1.setText(str(self.batcount)) 
            elif self.r2.isChecked()==True:
                self.ballcount+=1
                if self.ballcount>4:
                    self.message_box("You can't select more than four Bowlers")
                    self.ballcount-=1
                    self.point_avl+=r[0]
                    self.point_use-=r[0]
                else:
                    self.listWidget.takeItem(self.listWidget.row(item))
                    self.listWidget_2.addItem(item.text())
                    self.l2.setText(str(self.ballcount))
            elif self.r3.isChecked()==True:
                self.arcount+=1
                if self.arcount>3:
                    self.message_box("You can't select more than three All-Rounders")
                    self.arcount-=1
                    self.point_avl+=r[0]
                    self.point_use-=r[0]
                else:
                    self.listWidget.takeItem(self.listWidget.row(item))
                    self.listWidget_2.addItem(item.text())
                    self.l3.setText(str(self.arcount))
            elif self.r4.isChecked()==True:
                self.wkcount+=1 
                if self.wkcount>1:  
                    self.message_box("You can't select more than one Weeket-Keeper")
                    self.wkcount-=1
                    self.point_avl+=r[0]
                    self.point_use-=r[0]
                else:
                    self.listWidget.takeItem(self.listWidget.row(item))
                    self.listWidget_2.addItem(item.text()) 
                    self.l4.setText(str(self.wkcount))
        self.lineEdit_5.setText(str(self.point_avl))
        self.lineEdit_6.setText(str(self.point_use))

    #removing list2 items
    def removelist2(self,item):
            self.listWidget_2.takeItem(self.listWidget_2.row(item))
            c=cur.execute("SELECT ctg,[Values] FROM stats WHERE Player=='"+item.text()+"'")
            r=c.fetchone()
            self.point_avl+=r[1]
            self.point_use-=r[1]
            if r[0]=='bat':
                self.batcount-=1
                if self.r1.isChecked()==True:self.listWidget.addItem(item.text())
                self.l1.setText(str(self.batcount))
            if r[0]=='bwl':
                self.ballcount-=1
                if self.r2.isChecked()==True:self.listWidget.addItem(item.text())
                self.l2.setText(str(self.ballcount))
            if r[0]=='ar':
                self.arcount-=1
                if self.r3.isChecked()==True:self.listWidget.addItem(item.text())
                self.l3.setText(str(self.arcount))
            if r[0]=='wk':
                self.wkcount-=1
                if self.r4.isChecked()==True:self.listWidget.addItem(item.text())
                self.l4.setText(str(self.wkcount))
            self.lineEdit_5.setText(str(self.point_avl))
            self.lineEdit_6.setText(str(self.point_use))

    #evaluation
    def evaluate_show(self):
        self.eval=QtWidgets.QWidget()
        self.eval_score=Ui_Form()
        self.eval_score.setupUi(self.eval)
        self.eval.show()

    #team name
    def team_show(self):
        cur.execute("SELECT Name FROM teams")
        r=cur.fetchall()
        txt,ok=QtWidgets.QInputDialog.getText(MainWindow,"Team Name","Enter Your Team Name")
        if ok:
            for i in set(r):
                if txt==i[0]:
                    self.message_box("Name Already Exists")
                    break
            else:
                self.lineEdit_7.setText(txt)
                

    #open team
    def open_team(self):
        self.point_use=0
        self.point_avl=0
        self.batcount=0
        self.ballcount=0
        self.arcount=0
        self.wkcount=0
        sql="SELECT Name FROM teams"
        c=cur.execute(sql)
        teams=[]
        for row in set(c):
            teams.append(row[0])
        team, ok =QtWidgets.QInputDialog.getItem(MainWindow, "Team Selector",
                "Select Team", teams, 0, False)
        if ok and team:
            self.lineEdit_7.setText(team)
        sql1="SELECT Players, [Values] FROM teams where Name='"+team+"'"
        cur.execute(sql1)
        row=cur.fetchall()
        self.listWidget_2.clear()
        for i in range(len(row)):
            self.listWidget_2.addItem(row[i][0])
            self.point_use+=int(row[i][1])
            self.point_avl=1000-self.point_use
            c=cur.execute("SELECT ctg,[Values] FROM stats WHERE Player=='"+row[i][0]+"'")
            r=c.fetchone()
            if r[0]=='bat':
                self.batcount+=1
                self.l1.setText(str(self.batcount))
            if r[0]=='bwl':
                self.ballcount+=1
                self.l2.setText(str(self.ballcount))
            if r[0]=='ar':
                self.arcount+=1
                self.l3.setText(str(self.arcount))
            if r[0]=='wk':
                self.wkcount+=1
                self.l4.setText(str(self.wkcount))
        self.lineEdit_5.setText(str(self.point_avl))
        self.lineEdit_6.setText(str(self.point_use))
               

    #saving the team
    def save(self):
        db=sqlite3.connect("team.db")
        cur=db.cursor()
        item=[]
        
        if self.listWidget_2.count()!=11:
            self.message_box("Please Select 11 Players")
        
        else:
            for i in range(self.listWidget_2.count()):
                item.append(str(self.listWidget_2.item(i).text()))
            s=[]
            for i in item:
                cur.execute("SELECT [Values] FROM stats WHERE Player='"+i+"'")
                s.append(cur.fetchone()[0])
            List=tuple(zip(item,s))
            name=self.lineEdit_7.text()
            for i in range(len(List)):
                sql="INSERT INTO teams('Name','Players','Values') VALUES ('"+name+"','"+List[i][0]+"','"+str(List[i][1])+"');"
                cur.execute(sql)
            try:
                db.commit()
                self.message_box("Team Saved Successfuly")
            except:
                self.message_box("Error")
                db.rollback()
                

    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
